import type { AgentSeed } from './demo-types'
import { A, Y } from './demo-types'

/** Scripted conversations for the demo's agents. The text is placeholder content, written to read like real work. */
export const AGENT_SEED: Record<string, AgentSeed> = {
  claude: { name: 'Claude Code', shape: 'hexagon', color: '#f59e0b', main: [
    Y('9:02 AM', 'Checkout tests have been failing on main since last night. Can you find out why?'),
    A('9:03 AM', "I pulled the latest CI run and bisected the last 9 commits. The first failure is `a41c9f2`: a date fixture in `checkout.test.ts` is hard-coded and now falls on the wrong side of the DST change.\n1. `computeTaxWindow()` uses local time\n2. The fixture assumes UTC\n3. Two other suites share the same helper", { tool: 'Worked for 48s, called 6 tools' }),
    Y('9:05 AM', 'Fix the fixture, but use a fake clock instead of hard-coded dates.'),
    A('9:11 AM', 'Done. I added a fake clock in `test/utils/clock.ts`, updated 3 suites and ran everything: all 214 tests pass locally and in CI. PR #482 is open.', { tool: 'Worked for 3m 12s, called 11 tools' }),
    Y('9:12 AM', 'Does this change anything in production code?'),
    A('9:12 AM', 'No production code changed. I did notice `computeTaxWindow()` reads `Date.now()` directly, which is why the test was fragile. I can inject a clock parameter if you want that cleaned up.'),
    Y('9:14 AM', 'Yes, in a separate PR. Keep the diff small.'),
    A('9:21 AM', 'PR #483 is open: `computeTaxWindow(now = clock.now())` with a default, so no callers change. 6 files, +42 −18. Types check and all tests pass.', { tool: 'Worked for 5m 40s, called 14 tools' }),
    Y('9:23 AM', 'Ask Sam to review both PRs and post a summary in #eng.'),
    A('9:23 AM', 'Done. Sam is reviewing #482 and #483, and I posted this in #eng:\n**Checkout test fix** — a fake clock replaces hard-coded dates (#482); `computeTaxWindow` now takes an injectable clock (#483).', { tool: 'Worked for 9s, called 2 tools' }),
    Y('9:40 AM', 'Sam approved #482. Merge it once CI is green.'),
    A('9:41 AM', 'CI is green and #482 is merged to main. #483 is waiting on Sam, and I will merge it as soon as he approves.', { tool: 'Worked for 11s, called 3 tools' }),
  ] },
  codex: { name: 'Codex agent', shape: 'hexagon', color: '#14b8a6', main: [
    Y('11:02 AM', 'Consolidate the billing helpers. Three modules are doing almost the same thing.'),
    A('11:03 AM', 'I found `formatInvoice`, `formatReceipt` and `formatStatement` in three folders. They share about 80% of their logic and differ only in the header block.\n1. Create `billing/format.ts` with one `formatDocument(type, data)`\n2. Keep the old names as thin wrappers for one release\n3. Migrate the 11 call sites and delete the wrappers next sprint', { tool: 'Worked for 22s, called 5 tools' }),
    Y('11:06 AM', 'Good. Skip the wrappers, we have no external consumers.'),
    A('11:19 AM', 'Understood. I removed the wrappers and migrated all 11 call sites. Typecheck passes and the billing suite is green (62 tests). The diff is +188 −341.', { tool: 'Worked for 6m 40s, called 18 tools' }),
    Y('11:21 AM', 'Any behavior changes?'),
    A('11:21 AM', 'One: `formatStatement` used to round totals half-down, while the shared function rounds half-up like the other two. I added a test that pins the new behavior. If finance needs the old rounding I can parameterize it.'),
    Y('11:24 AM', 'Half-up is correct. Open the PR and link the ticket.'),
    A('11:26 AM', 'PR #479 is open and linked to BILL-212. I requested review from the billing owners.', { tool: 'Worked for 14s, called 3 tools' }),
    Y('11:30 AM', 'Also check whether any docs mention the old function names.'),
    A('11:32 AM', 'Two pages do: `docs/billing/formatting.mdx` and the changelog draft. I updated both in the same PR.', { tool: 'Worked for 1m 3s, called 6 tools' }),
  ] },
  pr: { name: 'PR agent', shape: 'pill', color: '#2563eb', main: [
    A('9:00 AM', 'Weekly review summary:\n1. 14 pull requests reviewed\n2. 3 waiting on the author\n3. 1 blocked on CI\n4. Median time to first review: 2h 10m', { tool: 'Worked for 31s, called 4 tools' }),
    Y('9:03 AM', 'Which one is blocked on CI?'),
    A('9:03 AM', '#471 (“Retry failed webhooks”). The lint job fails on a stale cache entry, not on the code. I cleared the cache and re-ran it.'),
    Y('9:08 AM', 'Did it pass?'),
    A('9:09 AM', 'Yes, all checks are green now. I left a note on the PR so the author knows nothing needs to change.', { tool: 'Worked for 1m 5s, called 2 tools' }),
    Y('9:12 AM', 'What are the three waiting on authors?'),
    A('9:12 AM', '1. #468 — requested changes on error handling, 4 days old\n2. #473 — missing tests for the new endpoint\n3. #476 — merge conflict with main\nWant me to nudge each author with the specific blocker?'),
    Y('9:14 AM', 'Yes, but only for #468 and #473. I will handle #476.'),
    A('9:15 AM', 'Done. I commented on #468 and #473 with the exact items to address. #476 is untouched.', { tool: 'Worked for 12s, called 2 tools' }),
    Y('9:20 AM', 'Which PRs are the riskiest to merge this week?'),
    A('9:21 AM', 'Two stand out:\n1. #465 changes the session token format and touches 14 files\n2. #471 changes webhook retry timing, which affects every integration\nI recommend a 24-hour staging soak for both. I can add that as a required check.', { tool: 'Worked for 38s, called 5 tools' }),
  ] },
  product: { name: 'Product Agent', shape: 'hexagon', color: '#2563eb', main: [
    Y('2:30 PM', 'Draft a one-page PRD for the notifications redesign. The audience is eng and design leads.'),
    A('2:34 PM', 'The first draft is in Files as `Notifications PRD.md`. Structure:\n1. Problem — users mute notifications because they cannot tell what needs action\n2. Goals — raise the action rate and cut opt-outs\n3. Non-goals — a full preferences rewrite\n4. Rollout — three options with trade-offs', { tool: 'Worked for 2m 30s, called 7 tools' }),
    Y('2:36 PM', 'Add success metrics. Be specific about baselines.'),
    A('2:39 PM', 'Added from the last 30 days of product analytics:\n1. Notification action rate: 11.8% now, target 18%\n2. Opt-out rate: 4.2% now, target under 3%\n3. Time to first action: 9m now, target under 5m\nBaselines are linked to the dashboards.', { tool: 'Worked for 1m 48s, called 5 tools' }),
    Y('2:41 PM', 'Which rollout option do you recommend?'),
    A('2:41 PM', 'Option 2: ship the grouped digest to 10% of workspaces first. It tests the main hypothesis, is reversible with a flag, and avoids touching the delivery pipeline until we have data.'),
    Y('2:44 PM', 'Agreed. Add a risks section and share it with design for comments.'),
    A('2:47 PM', 'Added risks (digest delay, duplicate alerts, mobile parity) with mitigations, and shared the doc with the design team. I will summarize their comments tomorrow morning.', { tool: 'Worked for 41s, called 4 tools' }),
    Y('2:50 PM', 'Create Linear tickets for the first milestone.'),
    A('2:53 PM', 'Created 6 tickets in the Notifications project: digest model, batching job, feature flag, settings UI, analytics events and QA plan. Each has an owner suggestion and an estimate.', { tool: 'Worked for 1m 12s, called 8 tools' }),
  ] },
  overlay: { name: 'Overlay', shape: 'circle', color: '#64748b', main: [
    Y('8:00 AM', 'What does tomorrow look like?'),
    A('8:00 AM', 'Tomorrow you have three meetings:\n1. 9:30 — Engineering standup\n2. 11:00 — Design review for the onboarding flow\n3. 3:00 — 1:1 with Priya\nYou have a free block from 12:00 to 2:30.', { tool: 'Worked for 6s, called 2 tools' }),
    Y('8:02 AM', 'Move the design review to the afternoon. Priya is out in the morning.'),
    A('8:03 AM', 'Priya is out until 1 PM, so I moved the design review to 2:00 and notified the three attendees. It conflicts with nothing.', { tool: 'Worked for 9s, called 3 tools' }),
    Y('8:06 AM', 'Prepare a brief for that meeting.'),
    A('8:09 AM', 'The brief is in Files:\n1. Decisions needed: onboarding steps (5 vs 3) and the empty-state design\n2. Data: completion drops 22% at step 4\n3. Open questions for design\nI attached the latest prototype link.', { tool: 'Worked for 2m 15s, called 6 tools' }),
    Y('8:10 AM', 'Draft a reply to the vendor email about the contract renewal.'),
    A('8:12 AM', 'The draft is in your Gmail drafts. It confirms the renewal, asks for the 10% volume discount discussed last quarter, and proposes a call on Thursday. Nothing has been sent.', { tool: 'Worked for 34s, called 4 tools' }),
    Y('8:14 AM', 'Add the renewal date to my calendar and set a reminder two weeks before.'),
    A('8:14 AM', 'Added “Vendor contract renewal” on the 28th with a reminder on the 14th.', { tool: 'Worked for 7s, called 2 tools' }),
  ] },
  fund: { name: 'Fundraising Agent', shape: 'triangle', color: '#16a34a', main: [
    Y('4:10 PM', "Who haven't we followed up with from last week's investor intros?"),
    A('4:11 PM', 'Four people have not received a follow-up:\n1. Lena Park, Ridgeline Capital — intro on Tuesday\n2. Marcus Webb, Alder Ventures — intro on Wednesday\n3. Two partners at Northwind — intro on Thursday\nAll four opened the deck.', { tool: 'Worked for 28s, called 5 tools' }),
    Y('4:14 PM', 'Draft follow-ups. Reference something specific from each conversation.'),
    A('4:22 PM', "I drafted four emails in Gmail. Each references a point from your meeting notes, such as Lena's question on net revenue retention and Marcus's interest in the self-hosting option.", { tool: 'Worked for 6m 02s, called 12 tools' }),
    Y('4:25 PM', 'Replace the metrics PDF with the data room link for Lena and Marcus.'),
    A('4:26 PM', 'Updated both drafts to link the data room instead of attaching the PDF.', { tool: 'Worked for 8s, called 2 tools' }),
    Y('4:30 PM', 'Send them tomorrow at 9 AM and log everything in the CRM.'),
    A('4:31 PM', 'Scheduled all four emails for 9:00 AM tomorrow and created the CRM activities with next steps and due dates.', { tool: 'Worked for 19s, called 6 tools' }),
    Y('4:34 PM', 'What does the pipeline look like now?'),
    A('4:35 PM', 'Pipeline summary:\n1. 3 partner meetings scheduled this week\n2. 5 firms in diligence\n3. 2 term sheets expected by the 30th\nSoft-circled so far: $2.1M of the $4M target.', { tool: 'Worked for 24s, called 4 tools' }),
  ] },
  support: { name: 'Support agent', shape: 'squircle', color: '#ea580c', main: [
    A('7:45 AM', 'Overnight summary: 12 new tickets. 9 were resolved from the help center and 3 need a human.', { tool: 'Worked for 41s, called 6 tools' }),
    Y('7:50 AM', 'Show me the three.'),
    A('7:50 AM', '1. Refund request from an annual-plan customer, 6 days after renewal\n2. SSO login loop for a team on the Okta integration\n3. Feature question from an enterprise trial about audit logs'),
    Y('7:53 AM', 'Refund is fine under policy. Process it and reply.'),
    A('7:55 AM', 'Refund of $240 processed and the customer notified. I also tagged the account so renewals show a reminder next year.', { tool: 'Worked for 18s, called 4 tools' }),
    Y('7:58 AM', 'What is going on with the SSO loop?'),
    A('7:59 AM', 'The redirect URI in their Okta app still points to the old domain. I sent them the correct URL and a short setup guide, and I will check back in two hours.', { tool: 'Worked for 52s, called 7 tools' }),
    Y('8:05 AM', 'And the enterprise trial question?'),
    A('8:06 AM', 'They asked whether audit logs can be exported to their SIEM. Yes: logs stream to S3 or can be pulled through the API. I drafted a reply with the setup steps and a link to the audit log docs.', { tool: 'Worked for 36s, called 5 tools' }),
    Y('8:08 AM', 'Send it, and let their account executive know.'),
    A('8:09 AM', 'Reply sent. I messaged the account executive in Slack with a summary and noted that audit-log export is a likely deciding factor for the trial.', { tool: 'Worked for 14s, called 4 tools' }),
    Y('8:15 AM', 'What were the most common topics in yesterday’s tickets?'),
    A('8:16 AM', 'Top three:\n1. Billing questions after plan changes (7 tickets)\n2. Webhook retries (5 tickets)\n3. Invite emails landing in spam (4 tickets)\nThe billing topic is up 40% from last week, so a help center article would likely deflect the most volume.', { tool: 'Worked for 48s, called 6 tools' }),
  ] },
  sales: { name: 'Sales agent', shape: 'blob', color: '#db2777', main: [
    Y('10:15 AM', 'Research Northwind before our call tomorrow.'),
    A('10:22 AM', 'The brief is in Files:\n1. About 400 employees, HQ in Chicago\n2. New VP of Operations since March\n3. Announced a data-platform migration in Q2\n4. Currently use three separate automation tools', { tool: 'Worked for 3m 14s, called 9 tools' }),
    Y('10:24 AM', 'What is our best angle?'),
    A('10:24 AM', 'Consolidation. Their migration creates a window to replace three tools with one control plane. Lead with the cost and audit-trail story, since the new VP owns both.'),
    Y('10:27 AM', 'Draft three questions for the discovery call.'),
    A('10:29 AM', '1. Which workflows break most often during the migration?\n2. Who approves new automation today, and how long does it take?\n3. What would a successful first 90 days look like?', { tool: 'Worked for 16s, called 2 tools' }),
    Y('10:32 AM', 'Who else at Northwind should we involve?'),
    A('10:33 AM', 'Three people:\n1. Dana Ruiz, Director of Platform — owns the migration timeline\n2. Chris Okafor, Security Lead — reviews every new vendor\n3. The VP of Operations as the economic buyer\nI suggest sending the security overview to Chris before the call.', { tool: 'Worked for 1m 05s, called 6 tools' }),
    Y('10:36 AM', 'Draft the pre-call email to Chris.'),
    A('10:38 AM', 'The draft is in Gmail. It introduces the call, attaches the security overview and SOC 2 report, and asks for any specific controls they want covered. It is short, four sentences.', { tool: 'Worked for 24s, called 4 tools' }),
    Y('10:40 AM', 'Create the opportunity in the CRM and set the stage to discovery.'),
    A('10:41 AM', 'Created “Northwind — Platform Consolidation” at the Discovery stage with the call date, the three contacts and the brief attached.', { tool: 'Worked for 13s, called 3 tools' }),
  ] },
  docs: { name: 'Docs agent', shape: 'cloud', color: '#7c3aed', main: [
    A('9:10 AM', 'I found 6 pages that still describe the old setup flow. Three are in Getting started and three are in the API guide.', { tool: 'Worked for 1m 20s, called 8 tools' }),
    Y('9:12 AM', 'Update the three in Getting started first.'),
    A('9:20 AM', 'Done. I rewrote the setup steps, replaced 4 screenshots and fixed 2 broken links. The preview is ready for review.', { tool: 'Worked for 5m 08s, called 15 tools' }),
    Y('9:22 AM', 'Add a short troubleshooting section to the last page.'),
    A('9:25 AM', 'Added three common errors with fixes: invalid token, missing webhook secret and a blocked callback URL. Each links to the relevant reference page.', { tool: 'Worked for 1m 42s, called 6 tools' }),
    Y('9:30 AM', 'Do the API guide pages next, in the same style.'),
    A('9:44 AM', 'Done. I updated the three API guide pages, regenerated the request examples from the OpenAPI spec and checked every code sample against the sandbox. All of them run.', { tool: 'Worked for 11m 20s, called 27 tools' }),
    Y('9:46 AM', 'Anything still out of date?'),
    A('9:47 AM', 'Two things: the webhook page references a deprecated header, and the SDK quickstart still pins version 1.4. I can fix both once the 1.5 release notes are final.', { tool: 'Worked for 32s, called 5 tools' }),
    Y('9:50 AM', 'Wait for 1.5. Open the PR for what we have and request review from the docs team.'),
    A('9:52 AM', 'PR #214 is open with 6 pages changed and requested from the docs team. I will update the SDK page when the release notes are published.', { tool: 'Worked for 15s, called 3 tools' }),
  ] },
}
