/**
 * Automation Run Workflow — durable execution of automation turns via the
 * Vercel Workflow SDK.
 *
 * Replaces the single-HTTP-request execution path with step-level durability:
 *   1. prepareExecution — create/reuse conversation (idempotent)
 *   2. executeActTurn — call the act route with the LLM (retryable)
 *   3. finalizeRun — settle generating messages (idempotent)
 *
 * If the process dies during any step, the workflow resumes from the last
 * completed step. Failed steps retry automatically (up to the SDK's limit).
 *
 * Trigger via: POST /api/v1/automations/{id}/run
 * Inspect via: npx workflow web
 *
 * Input must be fully serializable (strings, numbers, booleans) — no class
 * instances, functions, or server-only modules. HTTP calls pass auth via
 * the service token generated by the triggering route handler.
 */

import { RetryableError, FatalError } from "workflow"

export type AutomationRunWorkflowInput = {
  runId: string
  userId: string
  automationId: string
  name: string
  description: string
  instructions: string
  projectId?: string
  modelId?: string
  conversationId?: string
  turnId: string
  scheduledFor: number
  baseUrl: string
  serviceAuthHeader: string
  serviceToken: string
  actServiceToken: string
  finalizeServiceToken: string
  workspaceId?: string
}

export async function automationRunWorkflow(input: AutomationRunWorkflowInput) {
  "use workflow"

  // Step 1: Prepare — create or reuse conversation
  const prepared = await prepareExecution(input)

  // Step 2: Execute — call the act route (heavy LLM call, retryable)
  await executeActTurn({ ...input, conversationId: prepared.conversationId })

  // Step 3: Finalize — settle generating messages
  await finalizeRun({
    baseUrl: input.baseUrl,
    serviceAuthHeader: input.serviceAuthHeader,
    finalizeServiceToken: input.finalizeServiceToken,
    conversationId: prepared.conversationId,
    userId: input.userId,
    turnId: input.turnId,
  })

  return { conversationId: prepared.conversationId, runId: input.runId }
}

// ---------------------------------------------------------------------------
// Step 1: Prepare execution — create conversation if needed
// ---------------------------------------------------------------------------

async function prepareExecution(input: AutomationRunWorkflowInput): Promise<{
  conversationId: string
}> {
  "use step"

  // If conversation already exists (e.g. from a previous completed step),
  // reuse it — this makes the step idempotent on replay.
  if (input.conversationId) {
    return { conversationId: input.conversationId }
  }

  // Create a new conversation for this automation run via the internal API.
  const response = await fetch(`${input.baseUrl}/api/v1/automations/execute`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      [input.serviceAuthHeader]: input.serviceToken,
    },
    body: JSON.stringify({
      automationId: input.automationId,
      userId: input.userId,
      name: input.name,
      projectId: input.projectId,
      modelId: input.modelId,
    }),
  })

  if (!response.ok) {
    const text = await response.text().catch(() => '')
    throw new RetryableError(
      `Failed to create conversation: ${response.status} ${text}`,
    )
  }

  const data = await response.json() as { conversationId?: string }
  const conversationId = data.conversationId
  if (!conversationId) {
    throw new FatalError('Conversation creation returned no ID')
  }

  return { conversationId }
}

// ---------------------------------------------------------------------------
// Step 2: Execute the agent turn — call the act route
// ---------------------------------------------------------------------------

export function buildAutomationUserMessage(input: AutomationRunWorkflowInput): string {
  const scheduledAt = new Date(input.scheduledFor).toISOString()
  return [
    `Execute saved automation now: ${input.name}`,
    input.description ? `Description: ${input.description}` : '',
    `Scheduled for: ${scheduledAt}`,
    `Automation ID: ${input.automationId}`,
    '',
    'Current saved instructions to execute:',
    input.instructions,
  ].filter(Boolean).join('\n')
}

export function buildAutomationSystemPrompt(input: AutomationRunWorkflowInput): string {
  return [
    'You are running a scheduled automation for the user.',
    'Execute the stored automation instructions without asking clarifying questions.',
    'Do not create, draft, update, pause, delete, or propose a new automation. This run is already attached to an existing saved automation.',
    'If required auth, context, or tool access is missing, stop and write a concise failure summary.',
    'Only use tools that are clearly authorized by the stored automation and connected for this user.',
    'End with a concise summary of what was completed and what still needs attention.',
    '',
    `Automation name: ${input.name}`,
    input.description ? `Automation description: ${input.description}` : '',
  ].filter(Boolean).join('\n')
}

async function executeActTurn(input: AutomationRunWorkflowInput & {
  conversationId: string
}): Promise<{ ok: true }> {
  "use step"

  const response = await fetch(`${input.baseUrl}/api/v1/conversations/act`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'Idempotency-Key': `automation:${input.runId}:${input.turnId}`,
      [input.serviceAuthHeader]: input.actServiceToken,
      ...(input.workspaceId ? { 'x-overlay-workspace-id': input.workspaceId } : {}),
    },
    body: JSON.stringify({
      messages: [{
        id: input.turnId,
        role: 'user',
        parts: [{ type: 'text', text: buildAutomationUserMessage(input) }],
      }],
      systemPrompt: buildAutomationSystemPrompt(input),
      conversationId: input.conversationId,
      turnId: input.turnId,
      modelId: input.modelId,
      userId: input.userId,
      automationExecution: true,
      actAbortTimeoutMs: 720_000,
    }),
  })

  if (!response.ok) {
    const text = await response.text().catch(() => '')
    // 4xx errors are likely permanent (bad request, unauthorized, etc.)
    // 5xx errors are retryable (server error, timeout, etc.)
    if (response.status >= 400 && response.status < 500) {
      throw new FatalError(
        `Act route returned ${response.status}: ${text || 'Client error'}`,
      )
    }
    throw new RetryableError(
      `Act route returned ${response.status}: ${text || 'Server error'}`,
    )
  }

  // Drain the response body so the act route can finish and persist.
  if (response.body) {
    const reader = response.body.getReader()
    try {
      while (!(await reader.read()).done) {
        // Consume the UI stream
      }
    } finally {
      reader.releaseLock()
    }
  }

  return { ok: true }
}

// ---------------------------------------------------------------------------
// Step 3: Finalize — settle generating messages for the turn
// ---------------------------------------------------------------------------

async function finalizeRun(input: {
  baseUrl: string
  serviceAuthHeader: string
  finalizeServiceToken: string
  conversationId: string
  userId: string
  turnId: string
}): Promise<{ ok: true }> {
  "use step"

  // Settle generating messages — this is idempotent. If the turn was already
  // settled by the act route, this is a no-op.
  const response = await fetch(
    `${input.baseUrl}/api/v1/automations/execute`,
    {
      method: 'PATCH',
      headers: {
        'content-type': 'application/json',
        [input.serviceAuthHeader]: input.finalizeServiceToken,
      },
      body: JSON.stringify({
        conversationId: input.conversationId,
        userId: input.userId,
        turnId: input.turnId,
        status: 'completed',
        fallbackText: 'Automation run finished, but no final assistant response was saved.',
      }),
    },
  )

  // Non-fatal — the act route may have already settled the turn.
  if (!response.ok) {
    const text = await response.text().catch(() => '')
    // 404/409 means the conversation or turn is already settled — not an error
    if (response.status === 404 || response.status === 409) {
      return { ok: true }
    }
    throw new RetryableError(
      `Finalize failed: ${response.status} ${text}`,
    )
  }

  return { ok: true }
}
