import type { OverlayRuntimeConfigInput } from './overlayConfigSchema'

export const DEFAULT_OVERLAY_RUNTIME_CONFIG = {
  configVersion: 2,
  preset: 'saas-default',
  compliance: {
    profile: 'saas-default',
    minorMode: false,
    allowExternalProcessors: true,
    allowedProcessorIds: [],
    dataResidency: {
      required: false,
      allowedRegions: [],
    },
    retention: {},
  },
  features: {
    chat: true,
    files: true,
    memory: true,
    knowledge: true,
    automations: true,
    integrations: true,
    projects: true,
    skills: true,
    mcpServers: true,
    browserUse: true,
    sandboxes: true,
    webSearch: true,
    analytics: true,
    errorReporting: true,
    billing: true,
    webhooks: false,
    apiKeys: false,
    vectorSearch: true,
    modelRouting: true,
    sso: true,
    multiTenant: false,
  },
  providers: {
    auth: { provider: 'workos' },
    database: { provider: 'convex' },
    objectStorage: { provider: 'r2' },
    vectorSearch: { provider: 'convex' },
    embeddings: { provider: 'ai-gateway' },
    models: { provider: 'openrouter' },
    integrations: { provider: 'composio' },
    browser: { provider: 'browser-use' },
    sandbox: { provider: 'daytona' },
    webSearch: { provider: 'ai-gateway' },
    analytics: { provider: 'posthog' },
    errorReporting: { provider: 'sentry' },
    secrets: { provider: 'env' },
    rateLimit: { provider: 'convex' },
  },
  app: {
    baseUrl: 'https://getoverlay.io',
    deploymentEnvironment: 'production',
    cspConnectSrc: [],
    publicEnv: {},
  },
  auth: {
    provider: 'workos',
    allowDevFallbacks: false,
    workos: {},
    oidc: {},
    betterAuth: {},
  },
  billing: {
    provider: 'stripe',
    stripe: {
      mode: 'unknown',
    },
  },
  storage: {
    provider: 'r2',
    publicUrlPolicy: 'presigned',
    r2: {},
    s3: {},
  },
  llm: {
    gatewayProvider: 'openrouter',
    keySource: 'env',
    modelAllowlist: [],
  },
  integrations: {
    executor: {},
  },
  database: {
    provider: 'convex',
  },
  rateLimit: {
    redis: {
      failureMode: 'deny',
    },
  },
  capabilities: {
    billing: true,
    sso: true,
    apiKeys: false,
    webhooks: false,
    vectorSearch: true,
    automations: true,
    projects: true,
    skills: true,
    mcpServers: true,
    multiTenant: false,
  },
} satisfies OverlayRuntimeConfigInput
